unique_ids:
  assets:
    standard-page.html: ACWFJ7KW33TZOTXA5EQTV7MGKKTUSBAO
    theme.css: JGW7I3QMLJLWP7T5RZTPCISSNULXUJYD
  forms:
    Form1: 3WBXTGZTUKYBZYP4WKTGEKHGYEGHJXXS
  modules: {}
  scripts: {}
  server_modules: {}
